# Site settings
title: Granite.code AI
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://granitecode.ai/"
sourceurl: "https://github.com/Granite-Code/granitecode.github.io"
description: "AI code assistant"

permalink: /:title/

# Build settings
markdown: kramdown
